kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
coreDns:
  enabled: false
kubelet:
  enabled: true
nodeExporter:
  enabled: true
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    remoteWriteDashboards: false
datasource:
  prometheus:
    name: jason123-prometheus
  loki:
    name: jason123-loki
grafana:
  enabled: true
#  namespaceOverride: monitoring
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      multicluster:
        global:
          enabled: true
      annotations:
        findi.io/folder: jason123
    datasources:
      enabled: true
      uid: prometheus
      defaultDatasourceEnabled: true
      url: http://prometheus-mimir-query-frontend.monitoring.svc.cluster.local:8080/prometheus
      loki: http://prometheus-loki-distributed-gateway.monitoring.svc.cluster.local
      label: grafana_datasource
      # value of label that the configmaps with dashboards are set to
      labelValue: "1"
      annotations:
        asdfasd: asdfas
